
const int PRIV_M_READ_ALARM     = 0x0001;
const int PRIV_M_ENTER          = 0x0002;
const int PRIV_M_ENTER_KURVA    = 0x0004;
const int PRIV_M_ENTER_CALENDAR = 0x0008;
const int PRIV_M_CONFIRM_ALARM  = 0x0010;
const int PRIV_M_DISABLE_ALARM  = 0x0020;
const int PRIV_M_SET_TIME       = 0x0040;
const int PRIV_M_VAR_LIST       = 0x8000;
const int PRIV_M_ALL            = 0x7fffffff;


const int PRIV_M_ALL_ENTER      = 0x000e;
const int PRIV_M_ALL_ALARM      = 0x0031;

const int PRIV_M_OLD_LEVEL_1    = 0;
const int PRIV_M_OLD_LEVEL_2    = 0x0001;
const int PRIV_M_OLD_LEVEL_3    = 0x000f;
const int PRIV_M_OLD_LEVEL_4    = 0x007f;
const int PRIV_M_OLD_LEVEL_5    = 0x7fffffff;

